// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSdEZnYyfZP4dSOUjhvOR9y-eCrNwU1Ho',
    appId: '1:538866021360:web:52bf8e397ec2bc7d4ca335',
    messagingSenderId: '538866021360',
    projectId: 'flutter-ollama',
    authDomain: 'flutter-ollama.firebaseapp.com',
    storageBucket: 'flutter-ollama.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsa0Nh6c1cVWy5dzfBhQzXnfHDzQnfHz4',
    appId: '1:538866021360:android:92987e46fd8a26b24ca335',
    messagingSenderId: '538866021360',
    projectId: 'flutter-ollama',
    storageBucket: 'flutter-ollama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu25CCvD6oK5qGn4NF5b-gjXIIuHlM-a8',
    appId: '1:538866021360:ios:e915e4a17f84874e4ca335',
    messagingSenderId: '538866021360',
    projectId: 'flutter-ollama',
    storageBucket: 'flutter-ollama.appspot.com',
    iosBundleId: 'me.giuseppe.flutterOllama',
  );
}
