name: com.example.app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  google_fonts: ^6.2.1
  get: ^4.6.5
  cloud_firestore: ^4.17.3
  line_awesome_flutter: ^2.0.0
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
